/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package svmradikalmetode;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Andri
 */
public class menuDua extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menuDua() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        CmdPelatihan = new javax.swing.JButton();
        CmdPengujian = new javax.swing.JButton();
        CmdDatat = new javax.swing.JButton();
        CmdKamus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        DataMenu = new javax.swing.JMenu();
        KamusMenu = new javax.swing.JMenu();
        PelatihanMenu = new javax.swing.JMenu();
        PengujianMenu = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        CmdPelatihan.setText("PELATIHAN");
        CmdPelatihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdPelatihanActionPerformed(evt);
            }
        });

        CmdPengujian.setText("PENGUJIAN");
        CmdPengujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdPengujianActionPerformed(evt);
            }
        });

        CmdDatat.setText("DATA");
        CmdDatat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdDatatActionPerformed(evt);
            }
        });

        CmdKamus.setText("KAMUS");
        CmdKamus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdKamusActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Menggunakan Metode SVM");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("Analisis Sentimen Konten Radikal Melalui Dokumen Twitter");

        DataMenu.setText("Data");
        DataMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(DataMenu);

        KamusMenu.setText("Kamus");
        KamusMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KamusMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(KamusMenu);

        PelatihanMenu.setText("Pelatihan");
        PelatihanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PelatihanMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(PelatihanMenu);

        PengujianMenu.setText("Pengujian");
        PengujianMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PengujianMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(PengujianMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CmdKamus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CmdPelatihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CmdPengujian, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(CmdDatat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(CmdKamus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmdDatat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmdPelatihan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmdPengujian, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMenuMouseClicked
        try {
            // TODO add your handling code here:
            jDesktopPane1.removeAll();
            Data dT = new Data();
            dT.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
            jDesktopPane1.add(dT);
            dT.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuDua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DataMenuMouseClicked

    private void KamusMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KamusMenuMouseClicked
        try {
            // TODO add your handling code here:
            jDesktopPane1.removeAll();
            Kamus dT = new Kamus();
            dT.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
            jDesktopPane1.add(dT);
            dT.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuDua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_KamusMenuMouseClicked

    private void PelatihanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PelatihanMenuMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        Pelatihan dT = new Pelatihan();
        dT.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        jDesktopPane1.add(dT);
        dT.setVisible(true);
    }//GEN-LAST:event_PelatihanMenuMouseClicked

    private void PengujianMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengujianMenuMouseClicked
        try {
            // TODO add your handling code here:
            jDesktopPane1.removeAll();
            Pengujian dT = new Pengujian();
            dT.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
            jDesktopPane1.add(dT);
            dT.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuDua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PengujianMenuMouseClicked

    private void CmdPelatihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdPelatihanActionPerformed
        jDesktopPane1.removeAll();
        Pelatihan pelatihan = new Pelatihan();
        pelatihan.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        jDesktopPane1.add(pelatihan);
        pelatihan.setVisible(true);
    }//GEN-LAST:event_CmdPelatihanActionPerformed

    private void CmdPengujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdPengujianActionPerformed
        try {
            jDesktopPane1.removeAll();
            Pengujian pengujian = new Pengujian();
            pengujian.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
            jDesktopPane1.add(pengujian);
            pengujian.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuDua.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CmdPengujianActionPerformed

    private void CmdDatatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdDatatActionPerformed
        try {
            jDesktopPane1.removeAll();
            Data dT = new Data();
            dT.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
            jDesktopPane1.add(dT);
            dT.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuDua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CmdDatatActionPerformed

    private void CmdKamusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdKamusActionPerformed
        try {
            jDesktopPane1.removeAll();
            Kamus kamus = new Kamus();
            kamus.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
            jDesktopPane1.add(kamus);
            kamus.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuDua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CmdKamusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuDua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuDua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdDatat;
    private javax.swing.JButton CmdKamus;
    private javax.swing.JButton CmdPelatihan;
    private javax.swing.JButton CmdPengujian;
    private javax.swing.JMenu DataMenu;
    private javax.swing.JMenu KamusMenu;
    private javax.swing.JMenu PelatihanMenu;
    private javax.swing.JMenu PengujianMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
